python train.py -net squeezenet -gpu
python train.py -net mobilenet -gpu
python train.py -net mobilenetv2 -gpu
python train.py -net shufflenet -gpu
python train.py -net shufflenetv2 -gpu
python train.py -net vgg11 -gpu
python train.py -net vgg13 -gpu
python train.py -net vgg16 -gpu
python train.py -net vgg19 -gpu
python train.py -net densenet121 -gpu
python train.py -net densenet161 -gpu
python train.py -net densenet201 -gpu
python train.py -net googlenet -gpu
python train.py -net inceptionv3 -gpu
python train.py -net inceptionv4 -gpu
python train.py -net inceptionresnetv2 -gpu
python train.py -net xception -gpu
python train.py -net resnet18 -gpu
python train.py -net resnet34 -gpu
python train.py -net resnet50 -gpu
python train.py -net resnet101 -gpu
python train.py -net resnet152 -gpu
python train.py -net preactresnet18 -gpu
python train.py -net preactresnet34 -gpu
python train.py -net preactresnet50 -gpu
python train.py -net preactresnet101 -gpu
python train.py -net preactresnet152 -gpu
python train.py -net resnext50 -gpu
python train.py -net resnext101 -gpu
python train.py -net resnext152 -gpu
python train.py -net attention56 -gpu
python train.py -net attention92 -gpu
python train.py -net seresnet18 -gpu
python train.py -net seresnet34 -gpu
python train.py -net seresnet50 -gpu
python train.py -net seresnet101 -gpu
python train.py -net seresnet152 -gpu
python train.py -net nasnet -gpu
python train.py -net wideresnet -gpu
python train.py -net stochasticdepth18 -gpu
python train.py -net stochasticdepth34 -gpu
python train.py -net stochasticdepth50 -gpu
python train.py -net stochasticdepth101 -gpu